version: "3.7"

volumes:
  xdam-database-data:
  xdam-solr-data:

services:
  xdam_database:
    image: mariadb:10
    volumes:
    - xdam-database-data:/var/lib/mysql
    - ./docker/mariadb/initdb.d/:/docker-entrypoint-initdb.d
    ports:
    - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}

  xdam_httpd:
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
      args:
        UID: ${UID}
    ports:
      - 8001:80
    volumes:
      - ./public:/var/www/html
    depends_on:
      - xdam_php_fpm

  xdam_php_fpm:
    build:
      context: .
      dockerfile: docker/php-fpm/Dockerfile
      args:
        UID: ${UID}
    volumes:
      - ./:/usr/src/xdam
      - ${HOME}/.composer:/.composer
    depends_on:
      - xdam_database

  xdam_solr:
    image: solr:8
    ports:
      - 8983:8983
    volumes:
      - xdam-solr-data:/var/solr
